<?php
return [
    'fc-130' => [
        'name' => 'FC-130 小型物流无人机',
        'category' => '物流无人机',
        'payload' => '5kg',
        'endurance' => '续航约 60 分钟',
        'range' => '5km',
        'image' => 'assets/customer/logistics-50.png',
        'card_image' => 'assets/customer/cards/card-fc-130.jpg',
        'hero' => '面向最后一公里配送与复杂区域补给的小型智能物流平台',
        'summary' => '采用四旋翼构型，支持 GPS 自控导航、4G 数据链路和自动收放货物，可用于山区、海岛、园区等场景。',
        'features' => ['四旋翼构型', 'GPS/RTK 导航与定点悬停', '4G 网络与无线电通信', '支持自动下放货物与回收线缆'],
        'specs' => [
            '型号' => 'FC-130',
            '无人机类型' => '多旋翼',
            '最大载重' => '5kg',
            '最大起飞重量' => '12kg',
            '整机尺寸' => '650 × 650 × 500mm',
            '最大续航时间' => '60 分钟'
        ],
        'description' => 'FC-130 小型物流无人机可用于最后一公里物流场景，覆盖运输自动化、可视化、可控化和网络化流程。通过 GPS 自主导航、4G 网络和自动收放货系统，可在进入目标区域后完成货物下放，并在货物着陆后回收线缆并返回起飞点。',
        'gallery' => ['assets/customer/logistics-50.png']
    ],
    'fc-0510' => [
        'name' => 'FC-0510 智能物流无人机',
        'category' => '物流无人机',
        'payload' => '8kg',
        'endurance' => '文档未明确整机续航',
        'range' => '场景化任务飞行',
        'image' => 'assets/customer/logistics-150-1.png',
        'card_image' => 'assets/customer/logistics-150-1.png',
        'hero' => '自动化、可视化、可控化的智能物流配送平台',
        'summary' => '面向智慧物流与末端配送，集成 GPS 导航、AI 视觉识别、多传感器融合与自动挂载系统。',
        'features' => ['四旋翼构型', 'AI 视觉识别系统', 'GPS 自主导航 / 定点悬停 / 指点控制', '后台管理系统与微信小程序下单管理'],
        'specs' => [
            '型号' => 'FC-0510',
            '无人机厂家' => '北京飞行魔方科技',
            '无人机材质' => '碳纤维',
            '整机尺寸' => '740 × 780 × 600mm（不含桨）',
            '轴距' => '990mm',
            '额定载重' => '8kg'
        ],
        'description' => 'FC-0510 智能物流无人机面向智慧物流场景，通过 GPS 自控导航、4G 网络收发终端、AI 视觉识别与多种传感器支持配送与调度流程。无人机具备失控保护功能，可在异常情况下按设定逻辑飞往就近应急降落点。',
        'gallery' => ['assets/customer/logistics-150-1.png']
    ],
    'tf70' => [
        'name' => 'TF70 运输无人机',
        'category' => '物流无人机',
        'payload' => '建议负载 < 50kg',
        'endurance' => '视任务配置而定',
        'range' => '1500m 限距',
        'image' => 'assets/customer/logistics-50.png',
        'card_image' => 'assets/customer/cards/card-tf70.jpg',
        'hero' => '模块化、大载重、便携部署的运输无人机平台',
        'summary' => '采用前后对折四旋翼结构，支持避障雷达、防地雷达拓展和吊装载物栏模块，适合中型物流运输。',
        'features' => ['模块化机身', '快速插拔式电池', '前后置 FPV 图传', '可扩展避障雷达与防地雷达'],
        'specs' => [
            '对称轴距' => '228cm',
            '展开尺寸' => '180 × 176 × 74cm',
            '折叠尺寸' => '100 × 93 × 93cm',
            '最大载重' => '70kg（建议负载 < 50kg）',
            '额定起飞重量' => '88kg',
            '最大起飞重量' => '108kg'
        ],
        'description' => 'TF70 运输无人机采用轻量化机身与模块化设计，可搭载避障雷达和防地雷达，支持前置与后置 FPV 图像反馈。平台可用于中载重物资运输、吊挂作业和复杂地形条件下的运输任务。',
        'gallery' => ['assets/customer/logistics-50.png']
    ],
    'fc-5100n' => [
        'name' => 'FC-5100N 100 公斤运输无人机',
        'category' => '物流无人机',
        'payload' => '100kg',
        'endurance' => '空载 > 60 分钟',
        'range' => '中短程重载运输',
        'image' => 'assets/customer/logistics-100.png',
        'card_image' => 'assets/customer/cards/card-fc-5100n.jpg',
        'hero' => '100 公斤级重载运输平台，兼顾运力、效率与模块化部署',
        'summary' => '折叠机臂与快拆运输脚架设计，适合重载运输、应急投送与行业作业挂载。',
        'features' => ['最大载重 100kg', '18S 140AH 电池系统', '折叠机臂 / 快拆运输脚架', '空载续航超过 60 分钟'],
        'specs' => [
            '对称轴距' => '2660mm',
            '展开尺寸' => '2888 × 2888 × 1060mm',
            '折叠尺寸' => '1480 × 1480 × 1060mm',
            '最大起飞重量' => '190kg',
            '最大飞行速度' => '>15m/s',
            '螺旋桨尺寸' => '56in'
        ],
        'description' => 'FC-5100N 面向 100 公斤级运输任务，支持重载物流、物资投送和行业平台拓展。整机采用模块化折叠设计，兼顾运输便利性与大载重性能，适合应急消防、工业运输和山区物资配送等场景。',
        'gallery' => ['assets/customer/logistics-100.png', 'assets/customer/logistics-100-x13.png']
    ],
    'fc-ts150' => [
        'name' => 'FC-TS150 150 公斤物流无人机',
        'category' => '物流无人机',
        'payload' => '最大 150kg',
        'endurance' => '空载 > 50 分钟',
        'range' => '物流覆盖半径约 10km',
        'image' => 'assets/customer/logistics-150-2.png',
        'card_image' => 'assets/customer/logistics-150-2.png',
        'hero' => '面向大载重运输、挂载投送与行业物资搬运的平台',
        'summary' => '模块化机身，采用下折四轴八桨设计，支持避障雷达、防地雷达与前置 FPV 图传。',
        'features' => ['最大载重 150kg', 'GPS/RTK 自控定位导航', '4G 网络收发终端与 AI 视觉识别', '支持多机后台管理与微信小程序下单系统'],
        'specs' => [
            '型号' => 'FC-150',
            '材质' => '碳纤维、航空铝',
            '整机尺寸' => '210 × 195 × 110cm（不含桨）',
            '最大起飞重量' => '260kg',
            '额定载重' => '130kg',
            '电池' => '18S 30000mAh × 4'
        ],
        'description' => 'FC-TS150 适用于运输挂载物资、农业运输、光伏板挂载、高空抛投等多行业。平台支持 GPS 自主导航、定点悬停、指点控制和失控保护，在遇到大风、撞鸟或超出电子围栏等异常情况时可自动飞往应急降落点。',
        'gallery' => ['assets/customer/logistics-150-1.png', 'assets/customer/logistics-150-2.png', 'assets/customer/logistics-150-3.png'],
        'video' => 'assets/customer/logistics-150.mp4'
    ],
    'fc-ts300' => [
        'name' => 'FC-TS300 300 公斤物流无人机',
        'category' => '物流无人机',
        'payload' => '300kg',
        'endurance' => '空载 > 30 分钟',
        'range' => '10km',
        'image' => 'assets/customer/logistics-150-3.png',
        'card_image' => 'assets/customer/logistics-150-3.png',
        'hero' => '300 公斤级重载物流平台，可用于工业运输与自动物流流程',
        'summary' => '采用模块化大机身与分布式四电池设计，支持 AI 视觉识别和多机后台管理。',
        'features' => ['最大有效载重 300kg', '下折四轴八桨设计', 'AI 视觉识别与 4G 网络传输', '支持微信物流信息及航线查看、返航控制'],
        'specs' => [
            '型号' => 'FC-300',
            '最大起飞重量' => '600kg',
            '额定载重' => '300kg',
            '空机重量（含电池）' => '280kg',
            '最大可承受风速' => '12m/s',
            '最大起飞海拔高度' => '5000m'
        ],
        'description' => 'FC-TS300 面向高载重运输、农业运输、光伏板挂载与高空抛投等场景。通过提前设置多条飞行航线，平台可按预设规则匹配航线，执行自动起飞、定位下降和返航等任务，可用于自动物流流程。',
        'gallery' => ['assets/customer/logistics-150-3.png', 'assets/customer/logistics-150-2.png']
    ],
    'fc-f150pro' => [
        'name' => 'FC-F150pro 大载重消防投弹无人机飞行平台',
        'category' => '应急消防无人机',
        'payload' => '150kg',
        'endurance' => '文档突出作业能力',
        'range' => '复杂火灾场景应用',
        'image' => 'assets/customer/fire-hero.png',
        'card_image' => 'assets/customer/cards/card-fc-f150pro.jpg',
        'hero' => '面向复杂火灾场景的空中消防设备平台',
        'summary' => '可搭载 6 枚 × 25kg 水基灭火弹，面向森林火灾、城市建筑、危化品与灾害救援场景。',
        'features' => ['150kg 载重能力', '6 枚 × 25kg 水基灭火弹', '避障能力', '昼夜双光成像系统'],
        'specs' => [
            '平台定位' => '消防投弹无人机平台',
            '最大载重' => '150kg',
            '投弹能力' => '6 枚 × 25kg 水基灭火弹',
            '适用场景' => '森林火灾 / 城市建筑 / 危化品 / 灾害救援',
            '作业特点' => '可用于复杂环境作业',
            '成像系统' => '昼夜双光成像'
        ],
        'description' => 'FC-F150pro 面向传统消防中高风险、难抵达等场景需求，可用于空中侦查、定点投送等任务。具体作业方式和应用效果需结合实际场景、审批要求及项目配置确定。',
        'gallery' => ['assets/customer/fire-hero.png', 'assets/customer/fire-photo.jpg']
    ],
    'xh-v21' => [
        'name' => '星幻编队无人机 V2.1',
        'category' => '编队表演无人机',
        'payload' => '300g 灯光载荷',
        'endurance' => '集群飞行约 20 分钟 / 海平面续航 35 分钟',
        'range' => '控制半径 1000m',
        'image' => 'assets/customer/show-a7.png',
        'card_image' => 'assets/customer/cards/card-xh-v21.jpg',
        'hero' => '专业编队表演无人机，适合外场复杂环境下的大型空中演艺',
        'summary' => '升级动力系统、多星多频 RTK 定位与自主网通信系统，可用于支持编队任务。',
        'features' => ['多星多频 RTK 定位', '工业设计与升级动力系统', '图案航线设计地面软件', '自主网通信系统'],
        'specs' => [
            '轴距' => '33cm',
            '起飞重量' => '840g',
            '载荷' => '300g',
            '巡航速度' => '15m/s',
            '定位精度' => '±2cm（RTK 模式）',
            '灯光功率' => '36W 全彩'
        ],
        'description' => '星幻编队无人机 V2.1 可用于大型品牌活动、文旅夜游、城市庆典和商业发布会等场景。平台配套定位与通信系统，便于结合活动需求开展编队展示。',
        'gallery' => ['assets/customer/show-a3.png', 'assets/customer/show-a7.png', 'assets/customer/show-a8.png']
    ],
    'indoor-show' => [
        'name' => '室内编队无人机',
        'category' => '编队表演无人机',
        'payload' => '5W 灯光系统',
        'endurance' => '13 分钟',
        'range' => '<20m',
        'image' => 'assets/customer/show-line1.png',
        'card_image' => 'assets/customer/cards/card-indoor-show.jpg',
        'hero' => '适合室内活动与近距离沉浸式演出的轻量化编队平台',
        'summary' => '采用 UWB 定位，响应快、精度高，适合数字、字母和图案类室内编排效果。',
        'features' => ['UWB 定位，定位速度 <1s', '定位精度 10cm', '最小空中间距 0.3m', '建议表演时长 5 分钟，准备时间短'],
        'specs' => [
            '尺寸' => '208.67 × 208.67 × 93.92mm',
            '重量' => '190g',
            '轴距' => '165mm',
            '最大水平飞行速度' => '2m/s',
            '最大相对高度' => '<10m',
            '工作环境温度' => '-10°C 至 60°C'
        ],
        'description' => '室内编队无人机适合展会、发布会、商场中庭和科技馆等室内场景。平台体积轻小，定位快速，能够在有限空间内实现字母、数字和图案等视觉编队效果。',
        'gallery' => ['assets/customer/show-line1.png', 'assets/customer/show-line2.png', 'assets/customer/show-line3.png']
    ],
    'eggcraft' => [
        'name' => '蛋壳飞行器',
        'category' => '载人飞行器',
        'payload' => '90kg',
        'endurance' => '空载 > 50 分钟 / 负载 90kg > 15 分钟',
        'range' => '体验与试验性飞行场景',
        'image' => 'assets/customer/manned-hero.png',
        'card_image' => 'assets/customer/cards/card-eggcraft.jpg',
        'hero' => '轻型单人载人飞行平台，面向展示、体验与试验应用',
        'summary' => '采用折叠机臂和快拆运输脚架设计，具备较高机动性与运输便利性。',
        'features' => ['最大载重 90kg', '18S 140AH 电池', '折叠机臂 / 快拆运输脚架', '最大飞行速度 >15m/s'],
        'specs' => [
            '对称轴距' => '2660mm',
            '展开尺寸' => '3000 × 2888 × 1570mm',
            '折叠尺寸' => '1200 × 2050 × 1570mm',
            '整机重量（含电池）' => '116kg',
            '最大起飞重量' => '206kg（负载 90kg）',
            '电机功率' => '60kW（max）'
        ],
        'description' => '蛋壳飞行器是一款轻型载人飞行平台，适合低空体验、展示和试验性场景。整机采用大尺寸桨叶与高功率动力系统，兼顾稳定性和折叠运输能力。',
        'gallery' => ['assets/customer/manned-hero.png', 'assets/customer/manned-f.png', 'assets/customer/manned-l.png', 'assets/customer/manned-p.png', 'assets/customer/manned-t.png'],
        'video' => 'assets/customer/manned.mp4'
    ],
    'uav-platform' => [
        'name' => '低空飞行综合管理服务平台',
        'category' => '低空管理平台',
        'payload' => '多机型接入',
        'endurance' => '平台软件服务',
        'range' => 'PC / Android / iOS',
        'image' => 'assets/customer/fire-title.png',
        'card_image' => 'assets/customer/cards/card-uav-platform.jpg',
        'hero' => '面向无人机飞行数据监控、任务调度与站点规划的综合服务平台',
        'summary' => '支持跨平台操作与二次开发接口，可用于物流、应急响应、城市管理、安全、农业等多个领域。',
        'features' => ['飞机集群统计与动态监控', '飞机属性 / 模块挂载 / 对频管理', '航线设计与任务规划', '站点规划、航线绑定与任务执行联动'],
        'specs' => [
            '平台形态' => 'PC / Android / iOS',
            '开放能力' => '支持二次开发接口',
            '核心功能' => '实时监控飞行数据、拍摄状况与任务执行',
            '支持任务类型' => '巡检 / 安全 / 消防 / 物流投放 / 农业植保',
            '行业适配' => '政府、企业等单位定制化低空解决方案',
            '管理对象' => '无人机、飞行任务、起降站点'
        ],
        'description' => '低空飞行综合管理服务平台面向无人机飞行任务管理，支持多机集群管理、飞行数据统计、航线规划、站点规划与任务绑定。平台可用于无人机与作业任务管理，并支持按行业需求进行定制化配置。',
        'gallery' => ['assets/customer/fire-title.png']
    ],
];
