<?php
$cases = require __DIR__ . '/myfolder/cases.php';
$products = require __DIR__ . '/myfolder/products.php';
require __DIR__ . '/i18n.php';
$slug = isset($_GET['slug']) ? $_GET['slug'] : '';
$case = isset($cases[$slug]) ? $cases[$slug] : null;
if (!$case) { http_response_code(404); }
$productLinks = ['FC-130 小型物流无人机'=>'fc-130','FC-0510 智能物流无人机'=>'fc-0510','TF70 运输无人机'=>'tf70','FC-5100N 100 公斤运输无人机'=>'fc-5100n','FC-TS150 150 公斤物流无人机'=>'fc-ts150','FC-TS300 300 公斤物流无人机'=>'fc-ts300','FC-F150pro 大载重消防投弹无人机飞行平台'=>'fc-f150pro','星幻编队无人机 V2.1'=>'xh-v21','室内编队无人机'=>'indoor-show','蛋壳飞行器'=>'eggcraft','低空飞行综合管理服务平台'=>'uav-platform'];
?>
<!doctype html><html lang="<?= $lang === 'zh' ? 'zh-CN' : 'en' ?>"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= $case ? htmlspecialchars(localized($case['title']) . ' | ' . t('北京飞行魔方科技有限公司', 'Beijing Flicube Technology')) : htmlspecialchars(t('案例不存在', 'Case Not Found')) ?></title><link rel="stylesheet" href="assets/css/style.css"></head><body><?php render_header(); ?>
<section class="page-hero"><div class="container"><?php if (!$case): ?><div class="section-header"><div class="breadcrumb"><a href="<?= url_with_lang('index.php') ?>"><?= htmlspecialchars(t('首页','Home')) ?></a> / <?= htmlspecialchars(t('案例不存在','Case Not Found')) ?></div><h1><?= htmlspecialchars(t('未找到对应案例','Case Not Found')) ?></h1><p><?= htmlspecialchars(t('请返回应用案例页面重新选择。','Please return to the case list and choose again.')) ?></p><a class="btn btn-primary" href="<?= url_with_lang('cases.php') ?>"><?= htmlspecialchars(t('返回应用案例','Back to Cases')) ?></a></div><?php else: ?><div class="breadcrumb"><a href="<?= url_with_lang('index.php') ?>"><?= htmlspecialchars(t('首页','Home')) ?></a> / <a href="<?= url_with_lang('cases.php') ?>"><?= htmlspecialchars(t('应用案例','Cases')) ?></a> / <?= htmlspecialchars(localized($case['title'])) ?></div><div class="product-layout"><div class="photo"><img src="<?= htmlspecialchars($case['image']) ?>" alt="<?= htmlspecialchars(localized($case['title'])) ?>"></div><div><h1 class="detail-title"><?= htmlspecialchars(localized($case['title'])) ?></h1><p style="font-size:18px;color:#d5e4f8"><?= htmlspecialchars(localized($case['subtitle'])) ?></p><p><?= htmlspecialchars(localized($case['summary'])) ?></p><div class="hero-actions"><a class="btn btn-primary" href="<?= url_with_lang('contact.php') ?>"><?= htmlspecialchars(t('咨询该方案','Consult This Solution')) ?></a><a class="btn btn-secondary" href="<?= url_with_lang('cases.php') ?>"><?= htmlspecialchars(t('返回案例列表','Back to Cases')) ?></a></div></div></div><?php endif; ?></div></section>
<?php if ($case): ?><section class="section"><div class="container grid grid-2"><div class="dark-panel"><h2><?= htmlspecialchars(t('场景背景','Scenario Background')) ?></h2><ul class="feature-list"><?php foreach ($case['pain_points'] as $item): ?><li><?= htmlspecialchars(localized($item)) ?></li><?php endforeach; ?></ul></div><div class="dark-panel"><h2><?= htmlspecialchars(t('方案描述','Solution Description')) ?></h2><p><?= htmlspecialchars(localized($case['solution'])) ?></p></div></div></section><section class="section dark-section"><div class="container grid grid-3"><div class="dark-panel tall-panel"><h3><?= htmlspecialchars(t('对应产品','Related Products')) ?></h3><ul class="feature-list compact"><?php foreach ($case['products'] as $item): ?><li><?php if (isset($productLinks[$item]) && isset($products[$productLinks[$item]])): ?><a href="<?= url_with_lang('product.php', ['slug' => $productLinks[$item]]) ?>"><?= htmlspecialchars(localized($products[$productLinks[$item]]['name'])) ?></a><?php else: ?><?= htmlspecialchars($item) ?><?php endif; ?></li><?php endforeach; ?></ul></div><div class="dark-panel tall-panel"><h3><?= htmlspecialchars(t('实施流程','Implementation Process')) ?></h3><ul class="feature-list compact"><?php foreach ($case['process'] as $item): ?><li><?= htmlspecialchars(localized($item)) ?></li><?php endforeach; ?></ul></div><div class="dark-panel tall-panel"><h3><?= htmlspecialchars(t('交付与系统能力','Delivery and System Capability')) ?></h3><ul class="feature-list compact"><?php foreach ($case['deliverables'] as $item): ?><li><?= htmlspecialchars(localized($item)) ?></li><?php endforeach; ?></ul></div></div></section><section class="section"><div class="container cta-banner"><h2><?= htmlspecialchars(t('想进一步了解“','Want to explore “')) ?><?= htmlspecialchars(localized($case['title'])) ?><?= htmlspecialchars(t('”对应产品和实施方式？','” and its products and implementation approach?')) ?></h2><p><?= htmlspecialchars(t('欢迎联系北京飞行魔方科技有限公司，获取资料、参数说明与项目建议。','Contact Beijing Flicube Technology for brochures, specifications and project suggestions.')) ?></p><div class="hero-actions"><a class="btn btn-primary" href="<?= url_with_lang('contact.php') ?>"><?= htmlspecialchars(t('联系咨询','Contact Us')) ?></a><a class="btn btn-secondary" href="<?= url_with_lang('products.php') ?>"><?= htmlspecialchars(t('查看产品中心','View Products')) ?></a></div></div></section><?php endif; ?>
<footer class="footer"><div class="container footer-bottom"><div>© <?php echo date('Y'); ?> <?= htmlspecialchars(t('北京飞行魔方科技有限公司', 'Beijing Flicube Technology Co., Ltd.')) ?></div><div><?= htmlspecialchars(t('案例详情页', 'Case Detail')) ?></div></div></footer><script>(function(){var btn=document.querySelector('.mobile-menu-toggle');var panel=document.getElementById('mobile-menu-panel');if(!btn||!panel) return;btn.addEventListener('click',function(){var open=panel.classList.toggle('open');btn.setAttribute('aria-expanded', open ? 'true' : 'false');btn.textContent=open ? '✕' : '☰';});})();</script></body></html>
