<?php $cases = require __DIR__ . '/myfolder/cases.php'; ?>
<?php require __DIR__ . '/i18n.php'; ?>
<!doctype html>
<html lang="<?= $lang === 'zh' ? 'zh-CN' : 'en' ?>">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= htmlspecialchars(t('应用案例 | 北京飞行魔方科技有限公司', 'Cases | Beijing Flicube Technology')) ?></title><link rel="stylesheet" href="assets/css/style.css"></head>
<body>
<?php render_header(); ?>
<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="<?= url_with_lang('index.php') ?>"><?= htmlspecialchars(t('首页', 'Home')) ?></a> / <?= htmlspecialchars(t('应用案例', 'Cases')) ?></div><div class="section-header"><h1><?= htmlspecialchars(t('围绕真实低空场景构建产品与平台能力', 'Building product and platform capabilities around real low-altitude scenarios')) ?></h1><p><?= htmlspecialchars(t('从物流运输到应急消防，从文旅编队到载人展示，再到低空飞行综合管理平台，飞行魔方面向多行业提供解决方案。', 'From logistics transport to emergency firefighting, from drone shows to manned display, and from aircraft platforms to integrated low-altitude management, Flicube provides solutions across multiple industries.')) ?></p></div></div></section>
<section class="section dark-section"><div class="container grid grid-2"><?php foreach ($cases as $slug => $case): ?><article class="card case-card"><a href="<?= url_with_lang('case.php', ['slug' => $slug]) ?>" style="display:block;color:inherit;text-decoration:none;"><img src="<?= htmlspecialchars($case['image']) ?>" alt="<?= htmlspecialchars(localized($case['title'])) ?>"><div class="card-body"><h3><?= htmlspecialchars(localized($case['title'])) ?></h3><p><?= htmlspecialchars(localized($case['summary'])) ?></p><div class="hero-actions" style="margin-top:18px;"><span class="btn btn-secondary"><?= htmlspecialchars(t('查看案例详情', 'View Case Details')) ?></span></div></div></a></article><?php endforeach; ?></div></section>
<footer class="footer"><div class="container footer-bottom"><div>© <?php echo date('Y'); ?> <?= htmlspecialchars(t('北京飞行魔方科技有限公司', 'Beijing Flicube Technology Co., Ltd.')) ?></div><div><?= htmlspecialchars(t('应用案例页 · flicube.com', 'Cases Page · flicube.com')) ?></div></div></footer>
<script>(function(){var btn=document.querySelector('.mobile-menu-toggle');var panel=document.getElementById('mobile-menu-panel');if(!btn||!panel) return;btn.addEventListener('click',function(){var open=panel.classList.toggle('open');btn.setAttribute('aria-expanded', open ? 'true' : 'false');btn.textContent=open ? '✕' : '☰';});})();</script>
</body></html>
