<?php require __DIR__ . '/i18n.php'; ?>
<!doctype html>
<html lang="<?= $lang === 'zh' ? 'zh-CN' : 'en' ?>">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= htmlspecialchars(t('联系我们 | 北京飞行魔方科技有限公司', 'Contact | Beijing Flicube Technology')) ?></title><link rel="stylesheet" href="assets/css/style.css"></head>
<body>
<?php render_header(); ?>
<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="<?= url_with_lang('index.php') ?>"><?= htmlspecialchars(t('首页', 'Home')) ?></a> / <?= htmlspecialchars(t('联系我们', 'Contact')) ?></div><div class="section-header"><h1><?= htmlspecialchars(t('欢迎联系北京飞行魔方科技有限公司', 'Contact Beijing Flicube Technology')) ?></h1><p><?= htmlspecialchars(t('获取物流无人机、应急消防无人机、编队表演方案、载人飞行器资料及低空飞行综合管理服务平台方案。', 'Reach us for logistics drones, emergency firefighting drones, drone show solutions, manned aircraft information and low-altitude integrated platform solutions.')) ?></p></div></div></section>
<section class="section"><div class="container grid grid-2"><div class="contact-card emphasis"><h2><?= htmlspecialchars(t('联系方式', 'Contact Information')) ?></h2><p><strong><?= htmlspecialchars(t('公司名称：', 'Company: ')) ?></strong><?= htmlspecialchars(t('北京飞行魔方科技有限公司', 'Beijing Flicube Technology Co., Ltd.')) ?></p><p><strong><?= htmlspecialchars(t('联系邮箱：', 'Email: ')) ?></strong>pxzleo@126.com</p><p><strong><?= htmlspecialchars(t('公司地址：', 'Address: ')) ?></strong><?= htmlspecialchars(t('北京市昌平区史各庄街道生命科学园路北清创意园4-1楼', '4-1, Beiqing Creative Park, Life Science Park Road, Shigezhuang Subdistrict, Changping District, Beijing')) ?></p><p><strong><?= htmlspecialchars(t('核心业务：', 'Core Business: ')) ?></strong><?= htmlspecialchars(t('物流无人机、应急消防、编队表演、载人飞行器、低空管理平台', 'Logistics drones, emergency firefighting, drone shows, manned aircraft and low-altitude management platforms')) ?></p><p><strong><?= htmlspecialchars(t('合作方向：', 'Cooperation Areas: ')) ?></strong><?= htmlspecialchars(t('无人机采购、行业解决方案、项目合作、演艺活动、技术交流', 'UAV procurement, industry solutions, project cooperation, performance events and technical exchange')) ?></p></div><div class="dark-panel"><h2><?= htmlspecialchars(t('可提供支持', 'How We Can Help')) ?></h2><ul class="feature-list"><li><?= htmlspecialchars(t('物流无人机选型与运输解决方案设计', 'Logistics drone selection and transport solution design')) ?></li><li><?= htmlspecialchars(t('应急消防投弹无人机方案支持', 'Emergency firefighting drone solution support')) ?></li><li><?= htmlspecialchars(t('编队表演方案与现场实施咨询', 'Drone show planning and on-site implementation consulting')) ?></li><li><?= htmlspecialchars(t('载人飞行器展示与合作咨询', 'Manned aircraft showcase and cooperation consultation')) ?></li><li><?= htmlspecialchars(t('低空飞行综合管理服务平台集成与定制', 'Integrated low-altitude platform integration and customization')) ?></li></ul><div class="timeline"><div class="timeline-item"><strong><?= htmlspecialchars(t('需求沟通', 'Requirement Discussion')) ?></strong><br><?= htmlspecialchars(t('明确场景、产品方向和合作目标。', 'Clarify scenarios, product direction and collaboration goals.')) ?></div><div class="timeline-item"><strong><?= htmlspecialchars(t('方案整理', 'Solution Preparation')) ?></strong><br><?= htmlspecialchars(t('输出机型建议、参数重点和实施思路。', 'Provide aircraft suggestions, key specifications and implementation ideas.')) ?></div><div class="timeline-item"><strong><?= htmlspecialchars(t('正式联系', 'Formal Contact')) ?></strong><br><?= htmlspecialchars(t('可通过邮箱进一步沟通合作方案与产品资料。', 'Continue discussion via email for cooperation plans and product materials.')) ?></div></div></div></div></section>
<footer class="footer"><div class="container footer-bottom"><div>© <?php echo date('Y'); ?> <?= htmlspecialchars(t('北京飞行魔方科技有限公司', 'Beijing Flicube Technology Co., Ltd.')) ?></div><div><?= htmlspecialchars(t('联系我们页', 'Contact Page')) ?></div></div></footer>
<script>(function(){var btn=document.querySelector('.mobile-menu-toggle');var panel=document.getElementById('mobile-menu-panel');if(!btn||!panel) return;btn.addEventListener('click',function(){var open=panel.classList.toggle('open');btn.setAttribute('aria-expanded', open ? 'true' : 'false');btn.textContent=open ? '✕' : '☰';});})();</script>
</body></html>
