<?php
$news = require __DIR__ . '/myfolder/news.php';
require __DIR__ . '/i18n.php';
$slug = isset($_GET['slug']) ? $_GET['slug'] : '';
$item = isset($news[$slug]) ? $news[$slug] : null;
if (!$item) { http_response_code(404); }
?>
<!doctype html><html lang="<?= $lang === 'zh' ? 'zh-CN' : 'en' ?>"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= $item ? htmlspecialchars(localized($item['title']) . ' | ' . t('北京飞行魔方科技有限公司', 'Beijing Flicube Technology')) : htmlspecialchars(t('资讯不存在', 'News Not Found')) ?></title><link rel="stylesheet" href="assets/css/style.css"></head><body><?php render_header(); ?>
<section class="page-hero"><div class="container"><?php if (!$item): ?><div class="section-header"><div class="breadcrumb"><a href="<?= url_with_lang('index.php') ?>"><?= htmlspecialchars(t('首页','Home')) ?></a> / <?= htmlspecialchars(t('资讯不存在','News Not Found')) ?></div><h1><?= htmlspecialchars(t('未找到对应资讯','News Not Found')) ?></h1><p><?= htmlspecialchars(t('请返回新闻资讯页面重新选择。','Please return to the news page and choose again.')) ?></p><a class="btn btn-primary" href="<?= url_with_lang('news.php') ?>"><?= htmlspecialchars(t('返回新闻资讯','Back to News')) ?></a></div><?php else: ?><div class="breadcrumb"><a href="<?= url_with_lang('index.php') ?>"><?= htmlspecialchars(t('首页','Home')) ?></a> / <a href="<?= url_with_lang('news.php') ?>"><?= htmlspecialchars(t('新闻资讯','News')) ?></a> / <?= htmlspecialchars(localized($item['title'])) ?></div><div class="product-layout"><div class="photo"><img src="<?= htmlspecialchars($item['image']) ?>" alt="<?= htmlspecialchars(localized($item['title'])) ?>"></div><div><div class="eyebrow"><?= htmlspecialchars(localized($item['date'])) ?></div><h1 class="detail-title"><?= htmlspecialchars(localized($item['title'])) ?></h1><p style="font-size:18px;color:#d5e4f8"><?= htmlspecialchars(localized($item['summary'])) ?></p><div class="hero-actions"><a class="btn btn-primary" href="<?= url_with_lang('contact.php') ?>"><?= htmlspecialchars(t('联系咨询','Contact Us')) ?></a><a class="btn btn-secondary" href="<?= url_with_lang('news.php') ?>"><?= htmlspecialchars(t('返回资讯列表','Back to News')) ?></a></div></div></div><?php endif; ?></div></section>
<?php if ($item): ?><section class="section"><div class="container"><div class="dark-panel"><h2><?= htmlspecialchars(t('详细内容','Details')) ?></h2><?php foreach ($item['content'] as $paragraph): ?><p><?= htmlspecialchars(localized($paragraph)) ?></p><?php endforeach; ?></div></div></section><?php endif; ?>
<footer class="footer"><div class="container footer-bottom"><div>© <?php echo date('Y'); ?> <?= htmlspecialchars(t('北京飞行魔方科技有限公司', 'Beijing Flicube Technology Co., Ltd.')) ?></div><div><?= htmlspecialchars(t('新闻详情页', 'News Detail')) ?></div></div></footer><script>(function(){var btn=document.querySelector('.mobile-menu-toggle');var panel=document.getElementById('mobile-menu-panel');if(!btn||!panel) return;btn.addEventListener('click',function(){var open=panel.classList.toggle('open');btn.setAttribute('aria-expanded', open ? 'true' : 'false');btn.textContent=open ? '✕' : '☰';});})();</script>
</body></html>
