<?php $news = require __DIR__ . '/myfolder/news.php'; ?>
<?php require __DIR__ . '/i18n.php'; ?>
<!doctype html>
<html lang="<?= $lang === 'zh' ? 'zh-CN' : 'en' ?>">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= htmlspecialchars(t('新闻资讯 | 北京飞行魔方科技有限公司', 'News | Beijing Flicube Technology')) ?></title><link rel="stylesheet" href="assets/css/style.css"></head>
<body>
<?php render_header(); ?>
<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="<?= url_with_lang('index.php') ?>"><?= htmlspecialchars(t('首页', 'Home')) ?></a> / <?= htmlspecialchars(t('新闻资讯', 'News')) ?></div><div class="section-header"><h1><?= htmlspecialchars(t('产品动态与企业资讯', 'Product Updates and Company News')) ?></h1><p><?= htmlspecialchars(t('围绕公司产品、应用方向与企业相关信息，展示物流、应急、编队、载人及低空平台等业务内容。', 'News and updates around the company’s products, application directions and business development across logistics, emergency response, drone shows, manned aircraft and low-altitude platforms.')) ?></p></div></div></section>
<section class="section"><div class="container"><div class="media-grid" style="margin-bottom:28px;"><div class="media-card"><img src="assets/customer/logistics-100.png" alt="<?= htmlspecialchars(t('100 公斤无人机', '100 kg transport drone')) ?>"><p><?= htmlspecialchars(t('100 公斤级运输无人机', '100 kg transport drone')) ?></p></div><div class="media-card"><img src="assets/customer/show-line3.png" alt="<?= htmlspecialchars(t('室内编队设计图', 'Indoor drone show pattern design')) ?>"><p><?= htmlspecialchars(t('室内编队设计图', 'Indoor drone show pattern design')) ?></p></div></div><div class="grid grid-3"><?php foreach ($news as $slug => $item): ?><article class="card news-card"><a href="<?= url_with_lang('news-detail.php', ['slug' => $slug]) ?>" style="display:block;color:inherit;text-decoration:none;"><div class="card-body"><span class="news-date"><?= htmlspecialchars(localized($item['date'])) ?></span><h3><?= htmlspecialchars(localized($item['title'])) ?></h3><p><?= htmlspecialchars(localized($item['summary'])) ?></p><div class="hero-actions" style="margin-top:18px;"><span class="btn btn-secondary"><?= htmlspecialchars(t('查看详情', 'View Details')) ?></span></div></div></a></article><?php endforeach; ?></div></div></section>
<footer class="footer"><div class="container footer-bottom"><div>© <?php echo date('Y'); ?> <?= htmlspecialchars(t('北京飞行魔方科技有限公司', 'Beijing Flicube Technology Co., Ltd.')) ?></div><div><?= htmlspecialchars(t('新闻资讯页', 'News Page')) ?></div></div></footer><script>(function(){var btn=document.querySelector('.mobile-menu-toggle');var panel=document.getElementById('mobile-menu-panel');if(!btn||!panel) return;btn.addEventListener('click',function(){var open=panel.classList.toggle('open');btn.setAttribute('aria-expanded', open ? 'true' : 'false');btn.textContent=open ? '✕' : '☰';});})();</script>
</body></html>
